/** Fallback seed data used when Supabase is unreachable. */
export const SERVICES = [
  { id: 'seed-1', title: 'Wedding Video Editing', description: 'A breathtaking heirloom of your big day, edited with film-grade rhythm.', icon: 'Film', features: ['Full ceremony film', 'Highlight trailer', 'Audio sync & vows edit', 'Color grade'], ideal_for: 'Couples & families', delivery_time: '10–14 days', display_order: 1, is_published: true },
  { id: 'seed-2', title: 'Haldi Highlights', description: 'Vibrant, joyful cuts that capture every swirl of turmeric and laughter.', icon: 'Sun', features: ['Haldi highlight reel', 'Audio track sync', 'Slow-mo moments', 'Bright color grade'], ideal_for: 'Pre-wedding events', delivery_time: '4–6 days', display_order: 2, is_published: true },
  { id: 'seed-3', title: 'Pre-Wedding Cinematics', description: 'Storytelling films for the love before the vows — soft, romantic, timeless.', icon: 'Heart', features: ['Cinematic storyboard', 'Color matching', 'Music-driven edit', '4K master'], ideal_for: 'Couples', delivery_time: '7–10 days', display_order: 3, is_published: true },
  { id: 'seed-4', title: 'Bike Cinematic Editing', description: 'Adrenaline films — fast cuts, deep engine cuts, and cinematic landscapes.', icon: 'Bike', features: ['Cinematic color grade', 'Speed ramps', 'Sound design', 'Beat-synced cuts'], ideal_for: 'Riders & bike enthusiasts', delivery_time: '4–7 days', display_order: 4, is_published: true },
  { id: 'seed-5', title: 'Instagram Reels Editing', description: 'Scroll-stopping reels engineered for retention and shares.', icon: 'Smartphone', features: ['Trend-aware cuts', 'Beat-sync', 'Captions & stickers', 'Vertical 9:16 master'], ideal_for: 'Creators & brands', delivery_time: '24–48 hrs', display_order: 5, is_published: true },
  { id: 'seed-6', title: 'YouTube Video Editing', description: 'Watch-time optimized long-form edits with clean pacing and retention hooks.', icon: 'Youtube', features: ['Punchy intro & thumbnails', 'B-roll integration', 'Audio cleanup', 'Subtitle pass'], ideal_for: 'Creators & storytellers', delivery_time: '5–7 days', display_order: 6, is_published: true },
  { id: 'seed-7', title: 'Color Grading', description: 'Film-grade color science that gives every frame a signature mood.', icon: 'Palette', features: ['Shot matching', 'Creative LUTs', 'Skin tone protection', 'HDR-ready export'], ideal_for: 'Filmmakers & brands', delivery_time: '2–4 days', display_order: 7, is_published: true },
  { id: 'seed-8', title: 'Motion Graphics', description: 'Animated titles, transitions, and lower thirds that elevate every scene.', icon: 'Sparkles', features: ['Animated titles', 'Lower thirds', 'Seamless transitions', 'Logo stinger'], ideal_for: 'Brands & creators', delivery_time: '3–5 days', display_order: 8, is_published: true },
  { id: 'seed-9', title: 'Custom Editing Services', description: 'Have a unique vision? Let us craft a one-of-a-kind edit built around it.', icon: 'Wand2', features: ['Discovery call', 'Bespoke direction', 'Multi-format deliverables', 'Unlimited revisions'], ideal_for: 'Unique projects', delivery_time: 'Varies', display_order: 9, is_published: true },
];

export const PRICING = [
  { id: 'seed-p1', name: 'Starter', price_label: '₹4,999', period: 'per edit', description: 'Perfect for reels and short-form content.', features: ['1 reel or short edit', 'Beat-sync & trend aware', 'Captions included', '2 revisions', '3 day delivery'], delivery_note: 'MP4 vertical 9:16', is_popular: false, display_order: 1, is_published: true },
  { id: 'seed-p2', name: 'Premium', price_label: '₹14,999', period: 'per project', description: 'The full cinematic treatment.', features: ['Full highlight film', 'Cinematic color grade', 'Audio sync & cleanup', 'Sound design pass', '5 revisions', '7–10 day delivery'], delivery_note: '4K MP4 + vertical reel cut', is_popular: true, display_order: 2, is_published: true },
  { id: 'seed-p3', name: 'Custom', price_label: 'Let us talk', period: 'tailored scope', description: 'Bespoke for complex projects.', features: ['Discovery call first', 'Multi-format deliverables', 'Motion graphics & titles', 'Unlimited revisions', 'Priority timeline'], delivery_note: 'Flexible deliverables', is_popular: false, display_order: 3, is_published: true },
];

export const PROJECTS = [
  { id: 'seed-r1', title: 'Eternal Vows — Sneha & Arjun', category: 'Wedding', description: null, thumbnail_url: 'https://images.pexels.com/photos/1589216/pexels-photo-1589216.jpeg?auto=compress&cs=tinysrgb&w=900&h=600&fit=crop', video_url: null, tags: ['Wedding Film'], is_featured: true, is_published: true, display_order: 1 },
  { id: 'seed-r2', title: 'Golden Haldi Warmth', category: 'Haldi', description: null, thumbnail_url: 'https://images.pexels.com/photos/1024992/pexels-photo-1024992.jpeg?auto=compress&cs=tinysrgb&w=900&h=600&fit=crop', video_url: null, tags: ['Haldi Highlights'], is_featured: true, is_published: true, display_order: 2 },
  { id: 'seed-r3', title: 'Mountain Promise — Pre-Wedding', category: 'Pre-Wedding', description: null, thumbnail_url: 'https://images.pexels.com/photos/3035578/pexels-photo-3035578.jpeg?auto=compress&cs=tinysrgb&w=900&h=600&fit=crop', video_url: null, tags: ['Pre-Wedding Film'], is_featured: true, is_published: true, display_order: 3 },
  { id: 'seed-r4', title: 'Chrome & Thunder — KTM', category: 'Bike Shoots', description: null, thumbnail_url: 'https://images.pexels.com/photos/2111596/pexels-photo-2111596.jpeg?auto=compress&cs=tinysrgb&w=900&h=600&fit=crop', video_url: null, tags: ['Bike Cinematic'], is_featured: true, is_published: true, display_order: 4 },
  { id: 'seed-r5', title: 'City Lights Reel', category: 'Reels', description: null, thumbnail_url: 'https://images.pexels.com/photos/3734822/pexels-photo-3734822.jpeg?auto=compress&cs=tinysrgb&w=900&h=600&fit=crop', video_url: null, tags: ['Instagram Reel'], is_featured: false, is_published: true, display_order: 5 },
  { id: 'seed-r6', title: 'Cinematic Cafe Short', category: 'Cinematic Edits', description: null, thumbnail_url: 'https://images.pexels.com/photos/261909/pexels-photo-261909.jpeg?auto=compress&cs=tinysrgb&w=900&h=600&fit=crop', video_url: null, tags: ['Cinematic Short'], is_featured: true, is_published: true, display_order: 6 },
];

export const TESTIMONIALS = [
  { id: 'seed-t1', client_name: 'Sneha & Arjun', client_role: 'Wedding • Bengaluru', avatar_url: 'https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=160&h=160&fit=crop', rating: 5, content: 'Gowtham turned our raw wedding footage into a film my parents cried watching. Every beat was perfectly timed.', display_order: 1, is_published: true },
  { id: 'seed-t2', client_name: 'Karthik R', client_role: 'Bike Enthusiast', avatar_url: 'https://images.pexels.com/photos/220457/pexels-photo-220457.jpeg?auto=compress&cs=tinysrgb&w=160&h=160&fit=crop', rating: 5, content: 'My KTM video went viral. The speed ramps and engine sound design made it feel like a movie trailer.', display_order: 2, is_published: true },
  { id: 'seed-t3', client_name: 'Divya Lakshmi', client_role: 'Content Creator', avatar_url: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=160&h=160&fit=crop', rating: 5, content: 'Reels delivery was faster than any editor I used before — and they actually understood the trends.', display_order: 3, is_published: true },
  { id: 'seed-t4', client_name: 'Vikram & Aishu', client_role: 'Pre-Wedding • Ooty', avatar_url: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=160&h=160&fit=crop', rating: 5, content: 'The pre-wedding film felt like a short movie. Gowtham understood our story and made it visual.', display_order: 4, is_published: true },
];

export const FAQS = [
  { id: 'seed-f1', question: 'What type of edits do you make?', answer: 'Wedding films, haldi highlights, pre-wedding cinematics, bike cinematic edits, Instagram reels, YouTube edits, color grading, and motion graphics.', display_order: 1, is_published: true },
  { id: 'seed-f2', question: 'How long does delivery take?', answer: 'Standard reels ship within 24–48 hours. Highlight films take 4–7 days. Full wedding and cinematic projects typically take 7–14 days.', display_order: 2, is_published: true },
  { id: 'seed-f3', question: 'Can I request revisions?', answer: 'Yes. Starter gets 2, Premium gets 5, Custom includes unlimited revisions.', display_order: 3, is_published: true },
];
